
# File: .github/workflows/etl_etf_flows.yml
name: ETF Flows ETL (Farside -> CSV)
on:
  schedule:
    - cron: "0 1 * * 2-6"   # Tue-Sat 01:00 UTC (after US close)
  workflow_dispatch: {}
jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas lxml html5lib
      - name: Ensure state dir
        run: |
          mkdir -p .bot_state
      - name: Run ETL
        run: |
          python tools/etl_farside_to_csv.py
      - name: Commit CSV
        run: |
          git config user.email "bot@example.com"
          git config user.name "auto-etl-bot"
          git add .bot_state/btc_spot_etf_flows.csv
          git commit -m "auto: update ETF flows CSV" || echo "no changes"
          git push
