
# File: liquidity_monitor_workflow_v1_0_0.yml
name: Liquidity Monitor Bot v1.0.0

on:
  schedule:
    # 每周日 13:00 UTC == 周日 21:00 GMT+8
    - cron: "0 13 * * 0"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance python-dateutil

      - name: Run bot (send)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 可选人工备注（不填也可）
          FOMC_NOTE: ${{ secrets.FOMC_NOTE }}
          BTC_ETF_FLOWS_USD: ${{ secrets.BTC_ETF_FLOWS_USD }}
          GOLD_CB_PURCHASE_T: ${{ secrets.GOLD_CB_PURCHASE_T }}
          MODE: send
        run: |
          python liquidity_monitor_bot_v1_0_0.py

      - name: Status (optional dry-run)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          MODE: status
        run: |
          python liquidity_monitor_bot_v1_0_0.py
