
# File: .github/workflows/liquidity_monitor_workflow_v1_3_0.yml
name: Liquidity Monitor Bot v1.3.0
on:
  schedule:
    - cron: "0 13 * * 0"   # Sun 13:00 UTC == Sun 21:00 GMT+8
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance python-dateutil lxml html5lib
      - name: Sanity
        run: |
          python -m py_compile liquidity_monitor_bot_v1_3_0.py
          head -n 25 liquidity_monitor_bot_v1_3_0.py
      - name: Run bot (send)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          # Optional overrides
          GOLD_CB_PURCHASE_T: ${{ secrets.GOLD_CB_PURCHASE_T }}
          BTC_ETF_FLOWS_USD: ${{ secrets.BTC_ETF_FLOWS_USD }}
          # Data sources (Variables)
          WGC_CSV_PATH: ${{ vars.WGC_CSV_PATH }}
          WGC_CSV_URL: ${{ vars.WGC_CSV_URL }}
          IMF_USE_IFS: ${{ vars.IMF_USE_IFS }}
          IMF_COUNTRIES: ${{ vars.IMF_COUNTRIES }}
          IMF_FREQ: ${{ vars.IMF_FREQ }}
          IMF_INDICATOR_CANDIDATES: ${{ vars.IMF_INDICATOR_CANDIDATES }}
          BTC_ETF_FLOWS_CSV_PATH: ${{ vars.BTC_ETF_FLOWS_CSV_PATH }}
          BTC_ETF_FLOWS_CSV_URL: ${{ vars.BTC_ETF_FLOWS_CSV_URL }}
          BTC_ETF_API_URL: ${{ vars.BTC_ETF_API_URL }}
          FARSIDE_ALLDATA_URL: ${{ vars.FARSIDE_ALLDATA_URL }}
          MODE: send
        run: |
          python liquidity_monitor_bot_v1_3_0.py
