name: Liquidity Monitor Bot v1.5.2

on:
  schedule:
    - cron: "0 13 * * 1,3,5"   # Mon/Wed/Fri 13:00 UTC == 21:00 GMT+8
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance python-dateutil lxml html5lib numpy

      - name: Run bot (send)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          FRED_GOLD_SERIES_ID: ${{ vars.FRED_GOLD_SERIES_ID }}
          REG_WINDOW_M: ${{ vars.REG_WINDOW_M }}
          WGC_CSV_URL: ${{ vars.WGC_CSV_URL }}
          BTC_ETF_FLOWS_CSV_URL: ${{ vars.BTC_ETF_FLOWS_CSV_URL }}
          BTC_ETF_API_URL: ${{ vars.BTC_ETF_API_URL }}
          BTC_ETF_API_METHOD: ${{ vars.BTC_ETF_API_METHOD }}
          BTC_ETF_API_HEADERS: ${{ vars.BTC_ETF_API_HEADERS }}
          BTC_ETF_API_BODY: ${{ vars.BTC_ETF_API_BODY }}
          BTC_ETF_API_DATE_FIELD: ${{ vars.BTC_ETF_API_DATE_FIELD }}
          BTC_ETF_API_FLOW_FIELD: ${{ vars.BTC_ETF_API_FLOW_FIELD }}
          FARSIDE_ALLDATA_URL: ${{ vars.FARSIDE_ALLDATA_URL }}
          GOLD_FAIR_BASE: ${{ vars.GOLD_FAIR_BASE }}
          BETA_TIPS: ${{ vars.BETA_TIPS }}
          ALPHA_CB: ${{ vars.ALPHA_CB }}
          DXY_LOOKBACK_D: ${{ vars.DXY_LOOKBACK_D }}
          ETF_SHORT_D: ${{ vars.ETF_SHORT_D }}
          ETF_LONG_D: ${{ vars.ETF_LONG_D }}
          AUCTION_WINDOW_D: ${{ vars.AUCTION_WINDOW_D }}
          MODE: send
          VAL_GAP_PCT: ${{ vars.VAL_GAP_PCT }}
          ETF_WINDOW_CANDIDATES: ${{ vars.ETF_WINDOW_CANDIDATES }}
        run: |
          export GOLD_FAIR_BASE="${GOLD_FAIR_BASE:-REG}"
          python liquidity_monitor_bot_v1_5_2.py
