name: Liquidity Monitor Bot v1.5.5

on:
  workflow_dispatch:         # 手动运行按钮
  schedule:
    - cron: "0 13 * * 1,3,5" # 每周一/三/五 13:00 UTC ≈ 21:00 GMT+8

permissions:
  contents: read

concurrency:
  group: lmbot-1-5-5
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas requests numpy yfinance

      # —— 可选诊断步：不会阻断主流程（continue-on-error: true）——
      - name: ETF scoring helper (diagnostic)
        continue-on-error: true
        run: |
          python tools/etf_scoring_helper.py
        env:
          SOSOVALUE_API_KEY:         ${{ secrets.SOSOVALUE_API_KEY }}
          BTC_ETF_API_URL:           ${{ vars.BTC_ETF_API_URL }}
          BTC_ETF_API_METHOD:        ${{ vars.BTC_ETF_API_METHOD }}
          BTC_ETF_API_HEADERS:       ${{ vars.BTC_ETF_API_HEADERS }}
          BTC_ETF_API_BODY:          ${{ vars.BTC_ETF_API_BODY }}
          BTC_ETF_FLOWS_CSV_URL:     ${{ vars.BTC_ETF_FLOWS_CSV_URL }}
          BTC_ETF_CSV_DATE_FIELD:    ${{ vars.BTC_ETF_CSV_DATE_FIELD }}
          BTC_ETF_CSV_FLOW_FIELD:    ${{ vars.BTC_ETF_CSV_FLOW_FIELD }}
          ETF_LONG_D:                ${{ vars.ETF_LONG_D }}
          ETF_SHORT_D:               ${{ vars.ETF_SHORT_D }}
          DEBUG: "1"

      - name: Run Liquidity Monitor Bot v1.5.5
        run: |
          python liquidity_monitor_bot_v1_5_5.py
        env:
          # —— FRED / GOLD —— 
          FRED_API_KEY:              ${{ secrets.FRED_API_KEY }}
          FRED_GOLD_SERIES_ID:       ${{ vars.FRED_GOLD_SERIES_ID }}

          # —— WGC 央行购金：Raw 为主，Sheet 为兜底 —— 
          WGC_CSV_URL:               ${{ vars.WGC_CSV_URL }}
          WGC_SHEET_CSV_URL:         ${{ vars.WGC_SHEET_CSV_URL }}

          # —— ETF：API 优先，CSV 可不配（留空即不启用回退）——
          SOSOVALUE_API_KEY:         ${{ secrets.SOSOVALUE_API_KEY }}
          BTC_ETF_API_URL:           ${{ vars.BTC_ETF_API_URL }}
          BTC_ETF_API_METHOD:        ${{ vars.BTC_ETF_API_METHOD }}
          BTC_ETF_API_HEADERS:       ${{ vars.BTC_ETF_API_HEADERS }}
          BTC_ETF_API_BODY:          ${{ vars.BTC_ETF_API_BODY }}
          BTC_ETF_FLOWS_CSV_URL:     ${{ vars.BTC_ETF_FLOWS_CSV_URL }}
          BTC_ETF_CSV_DATE_FIELD:    ${{ vars.BTC_ETF_CSV_DATE_FIELD }}
          BTC_ETF_CSV_FLOW_FIELD:    ${{ vars.BTC_ETF_CSV_FLOW_FIELD }}
          ETF_LONG_D:                ${{ vars.ETF_LONG_D }}
          ETF_SHORT_D:               ${{ vars.ETF_SHORT_D }}

          # —— 估值/拍卖占位（可选）——
          VAL_GAP_PCT:               ${{ vars.VAL_GAP_PCT }}
          UST_AUCTIONS_DELTA:        ${{ vars.UST_AUCTIONS_DELTA }}

          # —— Telegram —— 
          TELEGRAM_BOT_TOKEN:        ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:          ${{ secrets.TELEGRAM_CHAT_ID }}
