name: Liquidity Monitor Bot v1.5.6
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1,3,5'  # Mon/Wed/Fri 21:00 GMT+8
    - cron: '0 13 * * 0'      # Sunday 21:00 GMT+8
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy yfinance

      - name: Permanent fix in repo (patch & commit)
        run: |
          python - <<'PY'
          import re
          p='liquidity_monitor_bot_v1_5_5.py'
          s=open(p,'r',encoding='utf-8').read()
          bad = 'or \n              "https://raw.githubusercontent.com/choosenobody/GoldTrendAlert/refs/heads/main/.bot_state/btc_spot_etf_flows.csv"'
          good= 'or "https://raw.githubusercontent.com/choosenobody/GoldTrendAlert/refs/heads/main/.bot_state/btc_spot_etf_flows.csv"'
          if bad in s:
              s=s.replace(bad,good)
          s=re.sub(r'(?m)^\s*text\s*=.*$', 'text = "\\n".join(lines)', s)
          open(p,'w',encoding='utf-8').write(s)
          print('permanent patch applied')
          PY
          git config user.email 'etl-bot@example.com'
          git config user.name  'etl-bot'
          git add liquidity_monitor_bot_v1_5_5.py
          git commit -m 'fix: permanent patch in v1_5_5.py' || echo 'no changes'
          git push || true

      - name: Run bot (v1.5.6)
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          SOSOVALUE_API_KEY: ${{ secrets.SOSOVALUE_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WGC_CSV_URL: ${{ vars.WGC_CSV_URL }}
          WGC_SHEET_CSV_URL: ${{ vars.WGC_SHEET_CSV_URL }}
          ETF_LONG_D: ${{ vars.ETF_LONG_D }}
          ETF_SHORT_D: ${{ vars.ETF_SHORT_D }}
          BTC_ETF_API_URL: ${{ vars.BTC_ETF_API_URL }}
          BTC_ETF_API_METHOD: ${{ vars.BTC_ETF_API_METHOD }}
          BTC_ETF_API_HEADERS: ${{ secrets.BTC_ETF_API_HEADERS }}
          BTC_ETF_API_BODY: ${{ vars.BTC_ETF_API_BODY }}
          BTC_ETF_FLOWS_CSV_URL: ${{ vars.BTC_ETF_FLOWS_CSV_URL }}
          VAL_GAP_PCT: ${{ vars.VAL_GAP_PCT }}
          UST_AUCTIONS_DELTA: ${{ vars.UST_AUCTIONS_DELTA }}
          FRED_GOLD_SERIES_ID: ${{ vars.FRED_GOLD_SERIES_ID }}
        run: |
          python liquidity_monitor_bot_v1_5_5.py
